=== limzykenneth/Cotta/schemas/file_upload.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "files_upload",
    "title": "Files Upload",
    "description": "Metadata of uploaded files",
    "type": "object",
    "properties": {
        "uid": {
            "type": "string",
            "description": "Unique ID identifying the file",
            "isIndex": true,
            "isUnique": true,
            "isAutoincrement": false
        },
        "content-type": {
            "type": "string",
            "description": "MIME type of the file"
        },
        "file_name": {
            "type": "string",
            "description": "File name of the file"
        },
        "file_description": {
            "type": "string",
            "description": "Description of the file"
        },
        "file_permalink": {
            "type": "string",
            "description": "Templated permalink of the file"
        },
        "file_size": {
            "type": "integer",
            "description": "Size of file in bytes",
            "minimum": 1
        },
        "file_owner": {
            "type": "string",
            "description": "Username of the file's owner"
        },
        "uploadExpire": {
            "type": "string",
            "description": "Timestamp for when upload link expire",
            "format": "date-time"
        },
        "created_at": {
            "type": "string",
            "description": "Timestamp for creation time",
            "format": "date-time"
        },
        "modified_at": {
            "type": "string",
            "description": "Timestamp for last modified time",
            "format": "date-time"
        },
        "saved_path": {
            "type": ["string", "null"],
            "description": "Local path to file"
        }
    },
    "required": ["uid", "content-type", "file_name", "file_description", "file_size", "file_owner", "uploadExpire", "modified_at", "saved_path"]
}

=== limzykenneth/Cotta/test/json/file_data_complete.json
{
  "content-type": "image/png",
  "file_name": "test.png",
  "file_description": "Test image",
  "created_at": "2020-11-04T15:02:03+00:00",
  "modified_at": "2020-11-04T15:02:03+00:00",
  "file_owner": "admin",
  "uploadExpire": "2020-11-04T16:02:03+00:00",
  "uid": "test_id",
  "file_permalink": "<%= root %>/uploads/test_id",
  "saved_path": null,
  "file_size": 1000000
}
